### ISSUE TITLE
Restart Option during game without dying

### ISSUE THREAD

**Issue by Eddykasp** [Eddykasp/platformer-html5-game#39]

**Comment by CleverlyCodes** [comment]
Hi @Eddykasp this is my first open source contribution. I'd like to try working on this one if it's alright with you.

**Comment by CleverlyCodes** [comment]
Kindly let me know if I missed something of if you prefer a certain way to do it https://github.com/Eddykasp/platformer-html5-game/pull/43

**Comment by CleverlyCodes** [comment]
Kindly let me know if I missed something or if you prefer to do it another way: https://github.com/Eddykasp/platformer-html5-game/pull/43
